# Generated by Django 3.2.16 on 2024-02-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240213_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='comment_id',
        ),
    ]
