# Generated by Django 3.2.16 on 2024-02-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_comment_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
    ]
